import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import TopNav from "../components/TopNav";
import Footer from "../components/Footer";
import BigTextBox from "../components/form/BigTextBox";
import Button from "../components/form/Button";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Search page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <TopNav></TopNav>

                <div className={styles.contentContainer}>
                    <div className={styles.searchContainer}>
                        <div className={styles.seachTitle}>Search
						</div>
                        <div className={styles.searchBox}>
                            <BigTextBox></BigTextBox>
                        </div>
                        <div className={styles.searchButton}>
                            <Button text="Search this"></Button>
                            <Button text="Howdy hey"></Button>
                        </div>
                        <div className={styles.searchDesc}>Done by Good Head</div>
                    </div>
                </div>
            </main>

            <Footer></Footer>
        </div>
    );
}
